### ISSUE TITLE
Which is the real dlex?

### ISSUE THREAD

**Issue by benwoodward** [pixelmonster-ou/dlex#55]
There seems to be 2 `dlex` repos, this one and the one here—https://github.com/liveforeverx/dlex, do they have different goals?

**Comment by jnylen** [comment]
Hi @benwoodward,

The one you linked is the real one. This one just has custom changes I did for https://github.com/pixelmonster-ou/metagraph such as reverse relations, translations etc.

I would suggest you go with @liveforeverx's repo as it's more clean and more up2date.

**Comment by benwoodward** [comment]
Thanks!
